setup quiz questions
personariseIT/Project-X pull request #4
Opened 2023-02-19 19:19 UTC by Femi-Benjamin

quiz questions

2023-02-19 21:37 UTC, kelani34 requested changes

2023-02-20 17:36 UTC, Femi-Benjamin commented on src/App.jsx
> +import Nextqs from "./pages/Nextqs";
imports fixed..

2023-02-20 17:38 UTC, kelani34 requested changes

2023-02-20 17:38 UTC, kelani34 commented on src/App.jsx
> +import Nextqs from "./pages/Nextqs";
I don't see it

2023-02-24 13:25 UTC, kelani34 approved these changes

2023-02-24 13:26 UTC, kelani34 approved these changes

2023-02-24 13:34 UTC, merged