career path
personariseIT/Project-X pull request #7
Opened 2023-03-03 15:09 UTC by Femi-Benjamin

Please check and confirm the Career path menu

2023-03-03 20:26 UTC, kelani34 requested changes

2023-03-03 20:26 UTC, kelani34 commented on package.json
> +    "@mui/material": "^5.11.11",
Why is the dependency changing?

2023-03-03 20:26 UTC, kelani34 commented on src/App.jsx
> +import DropDown from "./pages/DropDown";
Please always use index.js in pages to fix you import

2023-03-03 20:26 UTC, kelani34 commented on src/pages/Result.jsx
> +        <div className='bg-[#E4E4E4] h-screen'>
Please change the height. Its only needs to be h-full

2023-03-03 20:26 UTC, kelani34 commented on src/pages/Patth.jsx
> +                <div className='md:w-[657px] sm:w-auto md:h-[376.06px] sm:h-auto border sm:px-5 border-[#7C7E80] rounded-[7.11231px] bg-[#FFFFFF] text-center items-center'>
Please limit using sm: for media query. target the large screen- lg, the medium screen- md, then set a width for mobile

2023-03-03 20:26 UTC, kelani34 commented on src/pages/Result.jsx
>              <div className=' md:px-[400px] px-[30px] py-[30px]'>
Paddings are too much px-[400px] looks horrible on tablet or mobile screens. please stick to flex

2023-03-03 20:26 UTC, kelani34 commented on src/pages/Result.jsx
>              <div className=' md:px-[400px] px-[30px] py-[30px]'>
Pull from main I just fixed this

2023-03-04 07:16 UTC, Femi-Benjamin commented on src/pages/Patth.jsx
> +                <div className='md:w-[657px] sm:w-auto md:h-[376.06px] sm:h-auto border sm:px-5 border-[#7C7E80] rounded-[7.11231px] bg-[#FFFFFF] text-center items-center'>
Noted

2023-03-04 07:16 UTC, Femi-Benjamin commented on src/pages/Result.jsx
> +        <div className='bg-[#E4E4E4] h-screen'>
Height changed to Full

2023-03-04 07:28 UTC, Femi-Benjamin commented on src/App.jsx
> +import DropDown from "./pages/DropDown";
I tried it here did not work

2023-03-04 13:48 UTC, kelani34 approved these changes

2023-03-04 13:48 UTC, merged